FROM node:16.13.1-alpine3.14 as node

FROM node as builder

WORKDIR /app

COPY package.json /app
RUN npm install 
COPY . .
RUN npm run build

FROM node as final

RUN mkdir -p /home/node/app/build && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json .
COPY --chown=node:node package-lock.json .

USER node

RUN npm install --only=prod
RUN npm install serve
COPY --chown=node:node --from=builder /app/build ./build

CMD ["npm", "run", "serve"]