version: '3.8'

services: 
  api:
    restart: always
    depends_on:
      - mysql
    container_name: api
    image: lefantan/portfoliov2-backend
    build:
      context: ./api
      dockerfile: Dockerfile.production
    expose:
      [3001]
    environment:
      NODE_ENV: production
      GOOGLE_APPLICATION_CREDENTIALS: service-account.json
  client:
    restart: always
    container_name: client
    image: lefantan/portfoliov2-backend_client
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      [5000]
  nginx:
    restart: always
    container_name: nginx
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    volumes: 
      # persist data
      - data-volume:/var/lib/mysql
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"

volumes:
  data-volume: